# Generated by Django 6.0.5 on 2026-05-24 10:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CHEMICAL_NAME', models.CharField(max_length=100, unique=True)),
                ('CATEGORY', models.CharField(choices=[('TEXTILE_AUXILIARY', 'Textile Auxiliary'), ('PHARMA_GRADE', 'Pharma Grade'), ('SOLVENT', 'Solvent'), ('ACID_BASE', 'Acid Base')], max_length=100, unique=True)),
                ('CAS_NUMBER', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='category',
            new_name='CATEGORY',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='phone',
            new_name='PHONE',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='shop_name',
            new_name='SHOP_NAME',
        ),
        migrations.CreateModel(
            name='PriceListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_metric_ton', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity_available_mt', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('DISTRIBUTOR', models.ForeignKey(limit_choices_to={'role': 'DISTRIBUTOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
                ('PRODUCT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='marketplace.productlisting')),
            ],
            options={
                'unique_together': {('DISTRIBUTOR', 'PRODUCT')},
            },
        ),
        migrations.CreateModel(
            name='ProcurementOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_requested', models.PositiveIntegerField()),
                ('total_invoice', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('MANUFACTURER', models.ForeignKey(limit_choices_to={'role': 'MANUFACTURER'}, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='marketplace.pricelisting')),
            ],
        ),
    ]
