# Generated by Django 6.0.5 on 2026-05-24 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_productlisting_rename_category_customuser_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='SHOP_NAME',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
