# Generated by Django 6.0.5 on 2026-05-24 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_alter_customuser_shop_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='procurementorder',
            old_name='MANUFACTURER',
            new_name='ProcurementOrder',
        ),
        migrations.AddField(
            model_name='pricelisting',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
