# Generated by Django 6.0.5 on 2026-05-24 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_rename_manufacturer_procurementorder_procurementorder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricelisting',
            name='DISTRIBUTOR',
            field=models.ForeignKey(limit_choices_to={'CATEGORY': 'DISTRIBUTOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='productlisting',
            name='CATEGORY',
            field=models.CharField(choices=[('TEXTILE_AUXILIARY', 'Textile Auxiliary'), ('PHARMA_GRADE', 'Pharma Grade'), ('SOLVENT', 'Solvent'), ('ACID_BASE', 'Acid Base')], max_length=100),
        ),
    ]
