# Generated by Django 6.0.5 on 2026-05-24 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_alter_pricelisting_distributor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='procurementorder',
            old_name='ProcurementOrder',
            new_name='MANUFACTURER',
        ),
    ]
