# Generated by Django 6.0.5 on 2026-05-24 12:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_rename_procurementorder_procurementorder_manufacturer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procurementorder',
            name='MANUFACTURER',
            field=models.ForeignKey(limit_choices_to={'CATEGORY': 'MANUFACTURER'}, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
